"""initial_db

Revision ID: 289c32b49e46
Revises: 
Create Date: 2020-06-14 00:15:25.619441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289c32b49e46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=9), nullable=True),
    sa.Column('subject', sa.String(length=180), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
