SECRET_KEY = 'x2Cq7YohtXJ2MeXg6NVLcJAbXkJcGb7q'

PROPAGATE_EXCEPTIONS = True

# Database configuration
SQLALCHEMY_DATABASE_URI = 'mysql://sysdba:maolly88@127.0.0.1/rms_db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SHOW_SQLALCHEMY_LOG_MESSAGES = False

ERROR_404_HELP = False
